In [1]:
! pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.0-cp36-cp36m-win_amd64.whl 

In [2]:
! pip3 install torchvision

In [3]:
import torch
import torchvision

In [5]:
torch.ones(2,2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [7]:
torch.rand(2,2)

tensor([[ 0.3772,  0.5237],
        [ 0.2242,  0.5101]])

# Generating Seed
##### For the purpose of reproducibility

In [10]:
torch.manual_seed(0)
torch.rand(2,2)

tensor([[ 0.4963,  0.7682],
        [ 0.0885,  0.1320]])

#### How to do it in GPU ? 

In [12]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)