In [1]:
import torch
import numpy

In [8]:
a=torch.ones(2,2)
b=torch.ones(2,2)

In [10]:
# Reshaping

In [11]:
# If we need 4 columns
a.view(4)

tensor([ 1.,  1.,  1.,  1.])

In [12]:

a.view(4).size()

torch.Size([4])

In [13]:
# Element Addition/

a+b

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [16]:
c=torch.add(a,b)

In [15]:
# In-Place addition

In [17]:
c.add_(a)

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [19]:
c 
#  c no more matrix of 2

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [20]:
a-b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [21]:
a.sub(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [22]:
a.sub_(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [23]:
a*b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [25]:
torch.mul(a,b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [26]:
a.mul_(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [28]:
a/b

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [29]:
torch.div(a,b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [30]:
a.div_(b)

tensor([[ 0.,  0.],
        [ 0.,  0.]])

#  Tensor Mean


In [36]:
a=torch.tensor([1.0,2.0])
a.size()

torch.Size([2])

In [39]:
a.mean(dim=0)

tensor(1.5000)

In [42]:
a=torch.Tensor([[1.0,2.0],[3.0,5.0]])
a.size()

torch.Size([2, 2])

In [43]:
a.mean(dim=0)

tensor([ 2.0000,  3.5000])

In [44]:
a.mean(dim=1)

tensor([ 1.5000,  4.0000])

In [45]:
a.std(dim=0)

tensor([ 1.4142,  2.1213])

In [47]:
a.std(dim=1)

tensor([ 0.7071,  1.4142])