In [2]:
# Variables are wrapper around tensor that allows it to  accumulate its gradient

In [5]:
import torch
from torch.autograd import Variable

In [7]:
a=Variable(torch.ones(2,2),requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [8]:
torch.ones(2,2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [9]:
b=Variable(torch.ones(2,2),requires_grad=True)
b

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [12]:
##### Behaves same as tensor

In [11]:
a+b

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [13]:
#### Where it behaves differently

In [29]:
x=Variable(torch.ones(2),requires_grad=True)
x[1]

tensor(1.)

In [30]:
x

tensor([ 1.,  1.])

In [31]:
y=5*(x+1)**2
y

tensor([ 20.,  20.])

In [32]:
o=0.5*torch.sum(y)

In [33]:
o

tensor(20.)

In [34]:
o.backward()

In [35]:
x.grad

tensor([ 10.,  10.])